# Generated by Django 5.2.1 on 2025-05-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_evolucao_logedicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucao',
            name='visualizado',
            field=models.BooleanField(default=False),
        ),
    ]
